// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSerialPorts() {
  return window['go']['main']['App']['GetSerialPorts']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenPort(arg1) {
  return window['go']['main']['App']['OpenPort'](arg1);
}
