// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSerialPorts():Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function OpenPort(arg1:string):Promise<void>;
